version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.11-rc'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '13306:3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    command: mysqld --bind-address=0.0.0.0
    volumes:
      - ./docker/database/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - MAILER_DSN=smtp://mailer:1025
      - DATABASE_URL=mysql://root:password@database:3306/main


  nginx:
    image: nginx:1.23

    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8082:80"



volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
